name:                core-comp-unit
version:             0.1.0.0
github:              "bogo8liuk/core-comp-unit"
license:             MIT
author:              bogo8liuk
copyright:           2022 bogo8liuk

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/core-comp-unit#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.5.1
- time
- ghc
- ghc-paths

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-do-bind

library:
  source-dirs:
  - src
  exposed-modules:
  - FromCore

tests:
  core-comp-unit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - core-comp-unit
